import { Language, Translation } from './types';

export const TRANSLATIONS: Record<Language, Translation> = {
    en: {
        appName: 'Turbn',
        tagline: 'Find the perfect turban for any outfit.',
        getStarted: 'Get Started',
        uploadOutfit: 'Upload Outfit Photo',
        or: 'OR',
        pickColors: 'Pick Outfit Colors',
        shirtColor: 'Shirt Color',
        pantsColor: 'Pants Color',
        highlightsColor: 'Highlights Color (Optional)',
        getSuggestions: 'Get Turban Suggestions',
        uploadYourself: 'Upload a photo of yourself wearing a turban',
        uploadPrompt: 'Click on a suggested color to generate your new look!',
        generatingLook: 'Generating your look... This may take a moment.',
        yourLook: "Here's your new look!",
        download: 'Download',
        share: 'Share',
        tryAgain: 'Try Again',
        suggestions: 'Turban Suggestions',
        uploadOutfitPhoto: 'Upload Outfit Photo',
        pickColorsManually: 'Pick Colors Manually',
        analyzingColors: 'Analyzing outfit colors...',
        generatingSuggestions: 'Generating color suggestions...',
        errorColorDetection: 'Could not detect colors. Please try another photo.',
        errorSuggestions: 'Could not generate suggestions. Please try again.',
        errorImageGeneration: 'Could not generate image. Please try again.',
        selectTurban: 'Select Turban Color',
        saved: 'Look saved!',
        shared: 'Link copied to clipboard!',
        language: 'Language',
        editColors: 'Edit Colors',
        startOver: 'Start Over',
        yourOutfit: 'Your Outfit',
        savedLooks: 'Saved Looks',
        noSavedLooks: "You haven't saved any looks yet.",
        noSavedLooksCTA: 'Go back and create your first look!',
        deleteLook: 'Delete Look',
        generatingSuggestionsTitle: "Finding color harmonies...",
        generatingSuggestionsMessages: [
            "Consulting the color wheel...",
            "Analyzing complementary shades...",
            "Finding the perfect balance...",
            "Crafting stylish palettes...",
        ],
        generatingLookTitle: "Bringing your vision to life...",
        generatingLookMessages: [
            "Weaving your digital turban...",
            "Tailoring the perfect outfit...",
            "Adding the final touches...",
            "Capturing your unique style...",
            "Almost ready for the spotlight!",
        ],
        lookPalette: "Your Look's Palette",
        topType: 'Top Type',
        tshirt: 'T-Shirt',
        shirt: 'Shirt',
        kurta: 'Kurta',
        tabDiscover: 'Discover',
        tabStudio: 'Studio',
        tabLibrary: 'Library',
        tabInspo: 'Inspo',
        tabProfile: 'Profile',
        welcomeBadge: 'Instantly crafted style',
        welcomeTitle: 'Find your perfect turban palette',
        welcomeSwipe: 'Swipe to start',
        welcomeSkip: 'Skip',
        curatedLabel: 'Curated selection',
        discoverHeroLine1: 'Discover your',
        discoverHeroAccent: 'Color',
        discoverHeroSubtitle:
            'Let our AI find the ideal fabric shade that complements your silhouette and style.',
        cardUploadTitle: 'Upload outfit',
        cardUploadDesc: 'Trigger AI on your photo for curated turban recommendations.',
        cardUploadCta: 'AI generator',
        cardManualTitle: 'Manual selection',
        cardManualDesc: 'Design your look in the studio with the Turbn signature palette.',
        cardManualCta: 'Open studio',
        recentStyles: 'Recent styles',
        viewAll: 'View all',
        topTrendsSection: 'Top trends',
        trendMinimalTitle: 'The minimalist',
        trendMinimalDesc: 'Neutral palettes and sharp edges',
        trendMaxTitle: 'The maximalist',
        trendMaxDesc: 'Bold textures and heritage motifs',
        studioCanvasTitle: 'Studio',
        studioCanvasAccent: 'Canvas',
        studioCanvasSubtitle:
            'Refining the heritage aesthetic through color science and craftsmanship.',
        attireContext: 'Attire context',
        casual: 'Casual',
        formal: 'Formal',
        ceremonial: 'Ceremonial',
        topColor: 'Top color',
        bottomColor: 'Bottom color',
        recommendTurbanColors: 'Recommend turban colors',
        harmonyLogic: 'Harmony logic',
        harmonyIntro:
            'Your selection forms a deliberate foundation. When you generate suggestions, we translate it into harmonious turban pairings.',
        modelVersion: 'Model v04',
        uploadScreenTitle: 'Upload your',
        uploadScreenAccent: 'Outfit',
        uploadScreenSubtitle:
            'Our curator analyzes fabric depth, texture, and chroma to recommend the perfect turban pairing.',
        clickToCapture: 'Click to capture',
        browseOrCamera: 'Browse gallery or camera',
        selectedPreview: 'Selected preview',
        changePhoto: 'Change',
        engineVersion: 'Proprietary color theory engine v2.4',
        generateAestheticPreview: 'Generate aesthetic preview',
        recommendationTags: [
            'Recommended choice',
            'Minimalist aesthetic',
            'Heritage blend',
            'Curated pairing',
        ],
        whyMattersTitle: 'Why selection matters',
        whyMattersBody:
            'Color theory meets cultural signature. Each recommendation balances contrast, warmth, and occasion.',
        aestheticBalance: 'Aesthetic balance engine',
        culturalSignature: 'Cultural signature protocol',
        aiAnalyzingFabric: 'AI analyzing fabric textures…',
        saveToLibrary: 'Save to library',
        shareToGallery: 'Share to gallery',
        selectedColor: 'Selected color',
        inspoTitle: 'Inspiration',
        inspoBody:
            'A living moodboard of fabric, light, and silhouette — the same visual language as Recent styles, expanded with texture studies and palette experiments.',
        inspoGalleryLabel: 'Visual moodboard',
        inspoGallerySubtitle: 'Swipe through color stories, drape, and occasion — curated for the Turbn eye.',
        welcomeDragFull: 'Slide all the way right to continue',
        comingSoon: 'Coming soon',
        profileTitle: 'Profile',
        profileBody: 'Accounts and preferences will live here.',
        back: 'Back',
        regen: 'Regenerate',
        midnightPaletteTitle: 'The midnight palette',
        midnightPaletteSubtitle:
            'Curated chromatic pairings to elevate your silhouette with cultural authority and modern precision.',
        currentlyAvailable: 'Currently available',
        howToGenerateTitle: 'Create your preview',
        howToGenerateSubtitle: 'Use a sample model or your own photo for a personalized render.',
        useSampleModel: 'Sample model',
        useYourPhoto: 'Use my photo',
        sampleModelHint: 'AI-generated full-body look with your palette.',
        yourPhotoHint: 'Clear face or upper body; we dress you in the outfit and turban.',
        previewFromSample: 'Sample model render',
        previewFromYourPhoto: 'Personalized from your photo',
        previewFromOutfitPhoto: 'Turban preview on your outfit photo',
        shareNotAvailable: 'Sharing is not available on this device.',
        lookDetails: 'Look details',
        turbanColorLabel: 'Turban',
        topGarment: 'Top',
        bottomGarment: 'Bottom',
        close: 'Close',
        tapToView: 'Tap to view',
        previewSourceLabel: 'Preview',
        shareSuccess: 'Shared!',
        shareCopied: 'Image copied to clipboard',
        shareFailed: 'Could not share. Try Save or Download.',
    },
    pa: {
        appName: 'Turbn',
        tagline: 'ਕਿਸੇ ਵੀ ਪਹਿਰਾਵੇ ਲਈ ਸੰਪੂਰਨ ਦਸਤਾਰ ਲੱਭੋ।',
        getStarted: 'ਸ਼ੁਰੂ ਕਰੋ',
        uploadOutfit: 'ਪਹਿਰਾਵੇ ਦੀ ਫੋਟੋ ਅੱਪਲੋਡ ਕਰੋ',
        or: 'ਜਾਂ',
        pickColors: 'ਪਹਿਰਾਵੇ ਦੇ ਰੰਗ ਚੁਣੋ',
        shirtColor: 'ਕਮੀਜ਼ ਦਾ ਰੰਗ',
        pantsColor: 'ਪੈਂਟ ਦਾ ਰੰਗ',
        highlightsColor: 'ਹਾਈਲਾਈਟਸ ਰੰਗ (ਵਿਕਲਪਿਕ)',
        getSuggestions: 'ਦਸਤਾਰ ਲਈ ਸੁਝਾਅ ਪ੍ਰਾਪਤ ਕਰੋ',
        uploadYourself: 'ਦਸਤਾਰ ਪਹਿਨੇ ਹੋਏ ਆਪਣੀ ਇੱਕ ਫੋਟੋ ਅੱਪਲੋਡ ਕਰੋ',
        uploadPrompt: 'ਆਪਣਾ ਨਵਾਂ ਰੂਪ ਬਣਾਉਣ ਲਈ ਸੁਝਾਏ ਗਏ ਰੰਗ ਤੇ ਕਲਿੱਕ ਕਰੋ!',
        generatingLook: 'ਤੁਹਾਡਾ ਰੂਪ ਤਿਆਰ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ... ਇਸ ਵਿੱਚ ਕੁਝ ਸਮਾਂ ਲੱਗ ਸਕਦਾ ਹੈ।',
        yourLook: "ਇਹ ਰਿਹਾ ਤੁਹਾਡਾ ਨਵਾਂ ਰੂਪ!",
        download: 'ਡਾਊਨਲੋਡ ਕਰੋ',
        share: 'ਸਾਂਝਾ ਕਰੋ',
        tryAgain: 'ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ',
        suggestions: 'ਦਸਤਾਰ ਲਈ ਸੁਝਾਅ',
        uploadOutfitPhoto: 'ਪਹਿਰਾਵੇ ਦੀ ਫੋਟੋ ਅੱਪਲੋਡ ਕਰੋ',
        pickColorsManually: 'ਹੱਥੀਂ ਰੰਗ ਚੁਣੋ',
        analyzingColors: 'ਪਹਿਰਾਵੇ ਦੇ ਰੰਗਾਂ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...',
        generatingSuggestions: 'ਰੰਗ ਸੁਝਾਅ ਤਿਆਰ ਕੀਤੇ ਜਾ ਰਹੇ ਹਨ...',
        errorColorDetection: 'ਰੰਗਾਂ ਦਾ ਪਤਾ ਨਹੀਂ ਲੱਗ ਸਕਿਆ। ਕਿਰਪਾ ਕਰਕੇ ਕੋਈ ਹੋਰ ਫੋਟੋ ਅਜ਼ਮਾਓ।',
        errorSuggestions: 'ਸੁਝਾਅ ਤਿਆਰ ਨਹੀਂ ਕੀਤੇ ਜਾ ਸਕੇ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
        errorImageGeneration: 'ਚਿੱਤਰ ਤਿਆਰ ਨਹੀਂ ਕੀਤਾ ਜਾ ਸਕਿਆ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
        selectTurban: 'ਦਸਤਾਰ ਦਾ ਰੰਗ ਚੁਣੋ',
        saved: 'ਲੁੱਕ ਸੇਵ ਹੋ ਗਿਆ!',
        shared: 'ਲਿੰਕ ਕਲਿੱਪਬੋਰਡ ਤੇ ਕਾਪੀ ਕੀਤਾ ਗਿਆ!',
        language: 'ਭਾਸ਼ਾ',
        editColors: 'ਰੰਗ ਸੰਪਾਦਿਤ ਕਰੋ',
        startOver: 'ਨਵਾਂ ਸ਼ੁਰੂ ਕਰੋ',
        yourOutfit: 'ਤੁਹਾਡਾ ਪਹਿਰਾਵਾ',
        savedLooks: 'ਸੇਵ ਕੀਤੇ ਲੁੱਕ',
        noSavedLooks: 'ਤੁਸੀਂ ਹਾਲੇ ਤੱਕ ਕੋਈ ਲੁੱਕ ਸੇਵ ਨਹੀਂ ਕੀਤਾ ਹੈ।',
        noSavedLooksCTA: 'ਵਾਪਸ ਜਾਓ ਅਤੇ ਆਪਣਾ ਪਹਿਲਾ ਲੁੱਕ ਬਣਾਓ!',
        deleteLook: 'ਲੁੱਕ ਮਿਟਾਓ',
        generatingSuggestionsTitle: "ਰੰਗਾਂ ਦੀ ਇਕਸੁਰਤਾ ਲੱਭ ਰਿਹਾ ਹੈ...",
        generatingSuggestionsMessages: [
            "ਰੰਗ ਚੱਕਰ ਨਾਲ ਸਲਾਹ-ਮਸ਼ਵਰਾ...",
            "ਪੂਰਕ ਸ਼ੇਡਾਂ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ...",
            "ਸੰਪੂਰਨ ਸੰਤੁਲਨ ਲੱਭਣਾ...",
            "ਸਟਾਈਲਿਸ਼ ਪੈਲੇਟ ਤਿਆਰ ਕਰਨਾ...",
        ],
        generatingLookTitle: "ਤੁਹਾਡੇ ਦ੍ਰਿਸ਼ਟੀਕੋਣ ਨੂੰ ਜੀਵਨ ਵਿੱਚ ਲਿਆ ਰਿਹਾ ਹੈ...",
        generatingLookMessages: [
            "ਤੁਹਾਡੀ ਡਿਜੀਟਲ ਦਸਤਾਰ ਬੁਣ ਰਿਹਾ ਹੈ...",
            "ਸੰਪੂਰਨ ਪਹਿਰਾਵਾ ਤਿਆਰ ਕਰਨਾ...",
            "ਅੰਤਿਮ ਛੋਹਾਂ ਜੋੜਨਾ...",
            "ਤੁਹਾਡੀ ਵਿਲੱਖਣ ਸ਼ੈਲੀ ਨੂੰ ਕੈਪਚਰ ਕਰਨਾ...",
            "ਸਪਾਟਲਾਈਟ ਲਈ ਲਗਭਗ ਤਿਆਰ!",
        ],
        lookPalette: "ਤੁਹਾਡੇ ਲੁੱਕ ਦੀ ਪੈਲੇਟ",
        topType: 'ਸਿਖਰ ਦੀ ਕਿਸਮ',
        tshirt: 'ਟੀ-ਸ਼ਰਟ',
        shirt: 'ਕਮੀਜ਼',
        kurta: 'ਕੁਰਤਾ',
        tabDiscover: 'ਖੋਜ',
        tabStudio: 'ਸਟੂਡੀਓ',
        tabLibrary: 'ਲਾਇਬ੍ਰੇਰੀ',
        tabInspo: 'ਪ੍ਰੇਰਣਾ',
        tabProfile: 'ਪ੍ਰੋਫਾਈਲ',
        welcomeBadge: 'ਤੁਰੰਤ ਸਟਾਈਲ',
        welcomeTitle: 'ਆਪਣਾ ਸੰਪੂਰਨ ਦਸਤਾਰ ਪੈਲੇਟ ਲੱਭੋ',
        welcomeSwipe: 'ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਸਵਾਈਪ ਕਰੋ',
        welcomeSkip: 'ਛੱਡੋ',
        curatedLabel: 'ਚੁਣੀ ਹੋਈ ਚੋਣ',
        discoverHeroLine1: 'ਆਪਣਾ',
        discoverHeroAccent: 'ਰੰਗ',
        discoverHeroSubtitle:
            'ਸਾਡੀ AI ਤੁਹਾਡੀ ਸਿਲੂਟ ਅਤੇ ਸਟਾਈਲ ਨਾਲ ਮੇਲ ਖਾਂਦਾ ਸਹੀ ਰੰਗ ਲੱਭੇ।',
        cardUploadTitle: 'ਪਹਿਰਾਵਾ ਅੱਪਲੋਡ',
        cardUploadDesc: 'ਆਪਣੀ ਫੋਟੋ ਤੇ AI ਚਲਾਓ ਅਤੇ ਦਸਤਾਰ ਸੁਝਾਅ ਲਵੋ।',
        cardUploadCta: 'AI ਜਨਰੇਟਰ',
        cardManualTitle: 'ਹੱਥੀਂ ਚੋਣ',
        cardManualDesc: 'ਸਟੂਡੀਓ ਵਿੱਚ ਪੈਲੇਟ ਨਾਲ ਆਪਣਾ ਲੁੱਕ ਡਿਜ਼ਾਈਨ ਕਰੋ।',
        cardManualCta: 'ਸਟੂਡੀਓ ਖੋਲ੍ਹੋ',
        recentStyles: 'ਹਾਲੀਆ ਸਟਾਈਲ',
        viewAll: 'ਸਭ ਦੇਖੋ',
        topTrendsSection: 'ਟਾਪ ਟ੍ਰੈਂਡ',
        trendMinimalTitle: 'ਮਿਨੀਮਲਿਸਟ',
        trendMinimalDesc: 'ਨਿਊਟਰਲ ਪੈਲੇਟ ਅਤੇ ਤਿੱਖੇ ਕਿਨਾਰੇ',
        trendMaxTitle: 'ਮੈਕਸੀਮਲਿਸਟ',
        trendMaxDesc: 'ਬੋਲਡ ਬਣਾਟ ਅਤੇ ਵਿਰਾਸਤੀ ਨਮੂਨੇ',
        studioCanvasTitle: 'ਸਟੂਡੀਓ',
        studioCanvasAccent: 'ਕੈਨਵਸ',
        studioCanvasSubtitle:
            'ਰੰਗ ਵਿਗਿਆਨ ਅਤੇ ਕਾਰੀਗਰੀ ਰਾਹੀਂ ਵਿਰਾਸਤੀ ਸੁੰਦਰਤਾ।',
        attireContext: 'ਪਹਿਰਾਵੇ ਦਾ ਸੰਦਰਭ',
        casual: 'ਕੈਜ਼ੂਅਲ',
        formal: 'ਫਾਰਮਲ',
        ceremonial: 'ਰਸਮੀ',
        topColor: 'ਉੱਪਰਲਾ ਰੰਗ',
        bottomColor: 'ਹੇਠਲਾ ਰੰਗ',
        recommendTurbanColors: 'ਦਸਤਾਰ ਦੇ ਰੰਗ ਸੁਝਾਓ',
        harmonyLogic: 'ਹਾਰਮੋਨੀ ਲਾਜਿਕ',
        harmonyIntro:
            'ਤੁਹਾਡੀ ਚੋਣ ਇੱਕ ਨੀਂਹ ਬਣਾਉਂਦੀ ਹੈ। ਸੁਝਾਅ ਤੋਂ ਅਸੀਂ ਇਸਨੂੰ ਦਸਤਾਰ ਜੋੜਾਂ ਵਿੱਚ ਬਦਲਦੇ ਹਾਂ।',
        modelVersion: 'ਮਾਡਲ v04',
        uploadScreenTitle: 'ਅੱਪਲੋਡ ਕਰੋ',
        uploadScreenAccent: 'ਪਹਿਰਾਵਾ',
        uploadScreenSubtitle:
            'ਸਾਡੀ AI ਕੱਪੜੇ ਦੀ ਗਹਿਰਾਈ ਅਤੇ ਰੰਗ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰਦੀ ਹੈ।',
        clickToCapture: 'ਕੈਪਚਰ ਲਈ ਟੈਪ ਕਰੋ',
        browseOrCamera: 'ਗੈਲਰੀ ਜਾਂ ਕੈਮਰਾ',
        selectedPreview: 'ਚੁਣੀ ਝਲਕ',
        changePhoto: 'ਬਦਲੋ',
        engineVersion: 'ਕਲਰ ਥਿਊਰੀ ਇੰਜਨ v2.4',
        generateAestheticPreview: 'ਝਲਕ ਬਣਾਓ',
        recommendationTags: [
            'ਸਿਫਾਰਸ਼ੀ ਚੋਣ',
            'ਮਿਨੀਮਲ ਲੁੱਕ',
            'ਵਿਰਾਸਤ ਮਿਸ਼ਰਨ',
            'ਚੁਣੀ ਜੋੜੀ',
        ],
        whyMattersTitle: 'ਚੋਣ ਕਿਉਂ ਮਾਇਨੇ ਰੱਖਦੀ ਹੈ',
        whyMattersBody:
            'ਰੰਗ ਸਿਧਾਂਤ ਅਤੇ ਸੱਭਿਆਚਾਰਕ ਪਛਾਣ। ਹਰ ਸੁਝਾਅ ਕੰਟ੍ਰਾਸਟ ਅਤੇ ਮੌਕੇ ਅਨੁਸਾਰ ਹੈ।',
        aestheticBalance: 'ਸੁੰਦਰਤਾ ਸੰਤੁਲਨ ਇੰਜਨ',
        culturalSignature: 'ਸੱਭਿਆਚਾਰਕ ਦਸਤਖਤ ਪ੍ਰੋਟੋਕੋਲ',
        aiAnalyzingFabric: 'AI ਕੱਪੜੇ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰ ਰਿਹਾ ਹੈ…',
        saveToLibrary: 'ਲਾਇਬ੍ਰੇਰੀ ਵਿੱਚ ਸੇਵ',
        shareToGallery: 'ਗੈਲਰੀ ਨਾਲ ਸਾਂਝਾ',
        selectedColor: 'ਚੁਣਿਆ ਰੰਗ',
        inspoTitle: 'ਪ੍ਰੇਰਣਾ',
        inspoBody:
            'ਕੱਪੜਾ, ਰੋਸ਼ਨੀ ਅਤੇ ਸਿਲੂਟ — ਹਾਲੀਆ ਸਟਾਈਲ ਵਾਲੀ ਹੀ ਨਜ਼ਰ, ਹੋਰ ਬਣਾਟ ਅਤੇ ਰੰਗ ਪ੍ਰਯੋਗਾਂ ਨਾਲ।',
        inspoGalleryLabel: 'ਦਿੱਖ ਮੂਡਬੋਰਡ',
        inspoGallerySubtitle: 'ਰੰਗ ਕਹਾਣੀਆਂ, ਲੱਥ ਅਤੇ ਮੌਕਾ — ਚੁਣੀ ਝਲਕ।',
        welcomeDragFull: 'ਜਾਰੀ ਰੱਖਣ ਲਈ ਪੂਰੇ ਸੱਜੇ ਪਾਸੇ ਸਲਾਈਡ ਕਰੋ',
        comingSoon: 'ਜਲਦੀ ਆ ਰਿਹਾ ਹੈ',
        profileTitle: 'ਪ੍ਰੋਫਾਈਲ',
        profileBody: 'ਖਾਤਾ ਅਤੇ ਸੈਟਿੰਗਾਂ ਇੱਥੇ ਹੋਣਗੀਆਂ।',
        back: 'ਪਿੱਛੇ',
        regen: 'ਦੁਬਾਰਾ',
        midnightPaletteTitle: 'ਮਿਡਨਾਈਟ ਪੈਲੇਟ',
        midnightPaletteSubtitle:
            'ਤੁਹਾਡੀ ਸਿਲੂਟ ਲਈ ਚੁਣੇ ਰੰਗ ਜੋੜ।',
        currentlyAvailable: 'ਹੁਣ ਉਪਲਬਧ',
        howToGenerateTitle: 'ਆਪਣੀ ਝਲਕ ਬਣਾਓ',
        howToGenerateSubtitle: 'ਨਮੂਨਾ ਮਾਡਲ ਜਾਂ ਆਪਣੀ ਫੋਟੋ — ਤੁਹਾਡੇ ਲਈ ਖਾਸ ਰੂਪ।',
        useSampleModel: 'ਨਮੂਨਾ ਮਾਡਲ',
        useYourPhoto: 'ਮੇਰੀ ਫੋਟੋ',
        sampleModelHint: 'AI ਨਾਲ ਪੂਰਾ ਲੁੱਕ, ਤੁਹਾਡੇ ਰੰਗਾਂ ਨਾਲ।',
        yourPhotoHint: 'ਸਾਫ਼ ਚਿਹਰਾ ਜਾਂ ਉੱਪਰਲਾ ਹਿੱਸਾ; ਅਸੀਂ ਪਹਿਰਾਵਾ ਅਤੇ ਦਸਤਾਰ ਲਗਾਵਾਂਗੇ।',
        previewFromSample: 'ਨਮੂਨਾ ਮਾਡਲ ਝਲਕ',
        previewFromYourPhoto: 'ਤੁਹਾਡੀ ਫੋਟੋ ਤੋਂ ਵਿਅਕਤੀਗਤ',
        previewFromOutfitPhoto: 'ਤੁਹਾਡੀ ਫੋਟੋ ਤੇ ਦਸਤਾਰ ਝਲਕ',
        shareNotAvailable: 'ਇਸ ਡਿਵਾਈਸ ਤੇ ਸਾਂਝਾ ਉਪਲਬਧ ਨਹੀਂ।',
        lookDetails: 'ਲੁੱਕ ਵੇਰਵਾ',
        turbanColorLabel: 'ਦਸਤਾਰ',
        topGarment: 'ਉੱਪਰਲਾ',
        bottomGarment: 'ਹੇਠਲਾ',
        close: 'ਬੰਦ',
        tapToView: 'ਵੇਖਣ ਲਈ ਟੈਪ',
        previewSourceLabel: 'ਝਲਕ',
        shareSuccess: 'ਸਾਂਝਾ ਹੋ ਗਿਆ!',
        shareCopied: 'ਚਿੱਤਰ ਕਲਿੱਪਬੋਰਡ ਤੇ',
        shareFailed: 'ਸਾਂਝਾ ਨਹੀਂ ਹੋ ਸਕਿਆ। ਸੇਵ ਜਾਂ ਡਾਊਨਲੋਡ ਅਜ਼ਮਾਓ।',
    },
};

export const COMMON_SHIRT_COLORS = [
    { name: 'White', hex: '#FFFFFF' },
    { name: 'Black', hex: '#000000' },
    { name: 'Light Grey', hex: '#D3D3D3' },
    { name: 'Charcoal', hex: '#36454F' },
    { name: 'Navy Blue', hex: '#000080' },
    { name: 'Royal Blue', hex: '#4169E1' },
    { name: 'Sky Blue', hex: '#87CEEB' },
    { name: 'Maroon', hex: '#800000' },
    { name: 'Crimson Red', hex: '#DC143C' },
    { name: 'Baby Pink', hex: '#F4C2C2' },
    { name: 'Olive Green', hex: '#808000' },
    { name: 'Forest Green', hex: '#228B22' },
    { name: 'Mint Green', hex: '#98FF98' },
    { name: 'Beige', hex: '#F5F5DC' },
    { name: 'Mustard Yellow', hex: '#FFDB58' },
    { name: 'Lavender', hex: '#E6E6FA' },
    { name: 'Plum', hex: '#DDA0DD' },
    { name: 'Peach', hex: '#FFE5B4' },
];

export const COMMON_PANTS_COLORS = [
    { name: 'Black', hex: '#000000' },
    { name: 'Khaki', hex: '#C3B091' },
    { name: 'Denim Blue', hex: '#1E3A8A' },
    { name: 'Dark Grey', hex: '#A9A9A9' },
    { name: 'Light Grey', hex: '#D3D3D3' },
    { name: 'White', hex: '#FFFFFF' },
    { name: 'Brown', hex: '#A52A2A' },
    { name: 'Olive', hex: '#556B2F' },
    { name: 'Navy', hex: '#000080' },
    { name: 'Beige', hex: '#F5F5DC' },
    { name: 'Burgundy', hex: '#800020' },
    { name: 'Stone', hex: '#8B8C7A' },
    { name: 'Charcoal', hex: '#36454F' },
];

export const COMMON_HIGHLIGHTS_COLORS = [
    { name: 'Gold', hex: '#FFD700' },
    { name: 'Silver', hex: '#C0C0C0' },
    { name: 'White', hex: '#FFFFFF' },
    { name: 'Black', hex: '#000000' },
    { name: 'Crimson Red', hex: '#DC143C' },
    { name: 'Royal Blue', hex: '#4169E1' },
];

// Conceptually, this acts as our 'assets' folder for the landing page visuals
export const LANDING_PAGE_IMAGES = [
    'https://images.pexels.com/photos/15099685/pexels-photo-15099685.jpeg',
    'https://images.pexels.com/photos/29261349/pexels-photo-29261349.jpeg',
    'https://images.pexels.com/photos/29509894/pexels-photo-29509894.jpeg',
    'https://images.pexels.com/photos/29611425/pexels-photo-29611425.jpeg',
    'https://images.pexels.com/photos/29636303/pexels-photo-29636303.jpeg',
    'https://images.pexels.com/photos/2890747/pexels-photo-2890747.jpeg',
    'https://images.pexels.com/photos/15073750/pexels-photo-15073750.jpeg',
    'https://images.pexels.com/photos/18184057/pexels-photo-18184057.jpeg',
    'https://images.pexels.com/photos/13156810/pexels-photo-13156810.jpeg',
    'https://images.pexels.com/photos/15073762/pexels-photo-15073762.jpeg',
    'https://images.pexels.com/photos/5163938/pexels-photo-5163938.jpeg',
    'https://images.pexels.com/photos/14875566/pexels-photo-14875566.jpeg'
];

/** Welcome carousel — same family as Recent styles, curated for onboarding */
export const WELCOME_SLIDESHOW_IMAGES = [
    LANDING_PAGE_IMAGES[0],
    LANDING_PAGE_IMAGES[1],
    LANDING_PAGE_IMAGES[2],
    LANDING_PAGE_IMAGES[3],
];

const EXTRA_INSPRO_IMAGES = [
    'https://images.pexels.com/photos/3373716/pexels-photo-3373716.jpeg',
    'https://images.pexels.com/photos/1926764/pexels-photo-1926764.jpeg',
    'https://images.pexels.com/photos/1536619/pexels-photo-1536619.jpeg',
    'https://images.pexels.com/photos/1040945/pexels-photo-1040945.jpeg',
    'https://images.pexels.com/photos/2916814/pexels-photo-2916814.jpeg',
    'https://images.pexels.com/photos/985287/pexels-photo-985287.jpeg',
    'https://images.pexels.com/photos/2661255/pexels-photo-2661255.jpeg',
    'https://images.pexels.com/photos/1030946/pexels-photo-1030946.jpeg',
];

/** Inspo tab: recent-style imagery plus extra fabric & fashion references */
export const INSPO_GALLERY_IMAGES = [...new Set([...LANDING_PAGE_IMAGES, ...EXTRA_INSPRO_IMAGES])];