import { Language, Translation } from './types';

export const TRANSLATIONS: Record<Language, Translation> = {
    en: {
        appName: 'Turbn',
        tagline: 'Find the perfect turban for any outfit.',
        getStarted: 'Get Started',
        uploadOutfit: 'Upload Outfit Photo',
        or: 'OR',
        pickColors: 'Pick Outfit Colors',
        shirtColor: 'Shirt Color',
        pantsColor: 'Pants Color',
        getSuggestions: 'Get Turban Suggestions',
        uploadYourself: 'Upload a photo of yourself wearing a turban',
        uploadPrompt: 'Click on a suggested color to generate your new look!',
        generatingLook: 'Generating your look... This may take a moment.',
        yourLook: "Here's your new look!",
        download: 'Download',
        share: 'Share',
        tryAgain: 'Try Again',
        suggestions: 'Turban Suggestions',
        uploadOutfitPhoto: 'Upload Outfit Photo',
        pickColorsManually: 'Pick Colors Manually',
        analyzingColors: 'Analyzing outfit colors...',
        generatingSuggestions: 'Generating color suggestions...',
        errorColorDetection: 'Could not detect colors. Please try another photo.',
        errorSuggestions: 'Could not generate suggestions. Please try again.',
        errorImageGeneration: 'Could not generate image. Please try again.',
        selectTurban: 'Select Turban Color',
        saved: 'Look saved!',
        shared: 'Link copied to clipboard!',
        language: 'Language',
        editColors: 'Edit Colors',
        startOver: 'Start Over',
        yourOutfit: 'Your Outfit',
        savedLooks: 'Saved Looks',
        noSavedLooks: "You haven't saved any looks yet.",
        noSavedLooksCTA: 'Go back and create your first look!',
        deleteLook: 'Delete Look',
        generatingSuggestionsTitle: "Finding color harmonies...",
        generatingSuggestionsMessages: [
            "Consulting the color wheel...",
            "Analyzing complementary shades...",
            "Finding the perfect balance...",
            "Crafting stylish palettes...",
        ],
        generatingLookTitle: "Bringing your vision to life...",
        generatingLookMessages: [
            "Weaving your digital turban...",
            "Tailoring the perfect outfit...",
            "Adding the final touches...",
            "Capturing your unique style...",
            "Almost ready for the spotlight!",
        ],
    },
    pa: {
        appName: 'Turbn',
        tagline: 'ਕਿਸੇ ਵੀ ਪਹਿਰਾਵੇ ਲਈ ਸੰਪੂਰਨ ਦਸਤਾਰ ਲੱਭੋ।',
        getStarted: 'ਸ਼ੁਰੂ ਕਰੋ',
        uploadOutfit: 'ਪਹਿਰਾਵੇ ਦੀ ਫੋਟੋ ਅੱਪਲੋਡ ਕਰੋ',
        or: 'ਜਾਂ',
        pickColors: 'ਪਹਿਰਾਵੇ ਦੇ ਰੰਗ ਚੁਣੋ',
        shirtColor: 'ਕਮੀਜ਼ ਦਾ ਰੰਗ',
        pantsColor: 'ਪੈਂਟ ਦਾ ਰੰਗ',
        getSuggestions: 'ਦਸਤਾਰ ਲਈ ਸੁਝਾਅ ਪ੍ਰਾਪਤ ਕਰੋ',
        uploadYourself: 'ਦਸਤਾਰ ਪਹਿਨੇ ਹੋਏ ਆਪਣੀ ਇੱਕ ਫੋਟੋ ਅੱਪਲੋਡ ਕਰੋ',
        uploadPrompt: 'ਆਪਣਾ ਨਵਾਂ ਰੂਪ ਬਣਾਉਣ ਲਈ ਸੁਝਾਏ ਗਏ ਰੰਗ ਤੇ ਕਲਿੱਕ ਕਰੋ!',
        generatingLook: 'ਤੁਹਾਡਾ ਰੂਪ ਤਿਆਰ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ... ਇਸ ਵਿੱਚ ਕੁਝ ਸਮਾਂ ਲੱਗ ਸਕਦਾ ਹੈ।',
        yourLook: "ਇਹ ਰਿਹਾ ਤੁਹਾਡਾ ਨਵਾਂ ਰੂਪ!",
        download: 'ਡਾਊਨਲੋਡ ਕਰੋ',
        share: 'ਸਾਂਝਾ ਕਰੋ',
        tryAgain: 'ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ',
        suggestions: 'ਦਸਤਾਰ ਲਈ ਸੁਝਾਅ',
        uploadOutfitPhoto: 'ਪਹਿਰਾਵੇ ਦੀ ਫੋਟੋ ਅੱਪਲੋਡ ਕਰੋ',
        pickColorsManually: 'ਹੱਥੀਂ ਰੰਗ ਚੁਣੋ',
        analyzingColors: 'ਪਹਿਰਾਵੇ ਦੇ ਰੰਗਾਂ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...',
        generatingSuggestions: 'ਰੰਗ ਸੁਝਾਅ ਤਿਆਰ ਕੀਤੇ ਜਾ ਰਹੇ ਹਨ...',
        errorColorDetection: 'ਰੰਗਾਂ ਦਾ ਪਤਾ ਨਹੀਂ ਲੱਗ ਸਕਿਆ। ਕਿਰਪਾ ਕਰਕੇ ਕੋਈ ਹੋਰ ਫੋਟੋ ਅਜ਼ਮਾਓ।',
        errorSuggestions: 'ਸੁਝਾਅ ਤਿਆਰ ਨਹੀਂ ਕੀਤੇ ਜਾ ਸਕੇ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
        errorImageGeneration: 'ਚਿੱਤਰ ਤਿਆਰ ਨਹੀਂ ਕੀਤਾ ਜਾ ਸਕਿਆ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
        selectTurban: 'ਦਸਤਾਰ ਦਾ ਰੰਗ ਚੁਣੋ',
        saved: 'ਲੁੱਕ ਸੇਵ ਹੋ ਗਿਆ!',
        shared: 'ਲਿੰਕ ਕਲਿੱਪਬੋਰਡ ਤੇ ਕਾਪੀ ਕੀਤਾ ਗਿਆ!',
        language: 'ਭਾਸ਼ਾ',
        editColors: 'ਰੰਗ ਸੰਪਾਦਿਤ ਕਰੋ',
        startOver: 'ਨਵਾਂ ਸ਼ੁਰੂ ਕਰੋ',
        yourOutfit: 'ਤੁਹਾਡਾ ਪਹਿਰਾਵਾ',
        savedLooks: 'ਸੇਵ ਕੀਤੇ ਲੁੱਕ',
        noSavedLooks: 'ਤੁਸੀਂ ਹਾਲੇ ਤੱਕ ਕੋਈ ਲੁੱਕ ਸੇਵ ਨਹੀਂ ਕੀਤਾ ਹੈ।',
        noSavedLooksCTA: 'ਵਾਪਸ ਜਾਓ ਅਤੇ ਆਪਣਾ ਪਹਿਲਾ ਲੁੱਕ ਬਣਾਓ!',
        deleteLook: 'ਲੁੱਕ ਮਿਟਾਓ',
        generatingSuggestionsTitle: "ਰੰਗਾਂ ਦੀ ਇਕਸੁਰਤਾ ਲੱਭ ਰਿਹਾ ਹੈ...",
        generatingSuggestionsMessages: [
            "ਰੰਗ ਚੱਕਰ ਨਾਲ ਸਲਾਹ-ਮਸ਼ਵਰਾ...",
            "ਪੂਰਕ ਸ਼ੇਡਾਂ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ...",
            "ਸੰਪੂਰਨ ਸੰਤੁਲਨ ਲੱਭਣਾ...",
            "ਸਟਾਈਲਿਸ਼ ਪੈਲੇਟ ਤਿਆਰ ਕਰਨਾ...",
        ],
        generatingLookTitle: "ਤੁਹਾਡੇ ਦ੍ਰਿਸ਼ਟੀਕੋਣ ਨੂੰ ਜੀਵਨ ਵਿੱਚ ਲਿਆ ਰਿਹਾ ਹੈ...",
        generatingLookMessages: [
            "ਤੁਹਾਡੀ ਡਿਜੀਟਲ ਦਸਤਾਰ ਬੁਣ ਰਿਹਾ ਹੈ...",
            "ਸੰਪੂਰਨ ਪਹਿਰਾਵਾ ਤਿਆਰ ਕਰਨਾ...",
            "ਅੰਤਿਮ ਛੋਹਾਂ ਜੋੜਨਾ...",
            "ਤੁਹਾਡੀ ਵਿਲੱਖਣ ਸ਼ੈਲੀ ਨੂੰ ਕੈਪਚਰ ਕਰਨਾ...",
            "ਸਪਾਟਲਾਈਟ ਲਈ ਲਗਭਗ ਤਿਆਰ!",
        ],
    },
};

export const COMMON_SHIRT_COLORS = [
    { name: 'White', hex: '#FFFFFF' },
    { name: 'Black', hex: '#000000' },
    { name: 'Light Grey', hex: '#D3D3D3' },
    { name: 'Charcoal', hex: '#36454F' },
    { name: 'Navy Blue', hex: '#000080' },
    { name: 'Royal Blue', hex: '#4169E1' },
    { name: 'Sky Blue', hex: '#87CEEB' },
    { name: 'Maroon', hex: '#800000' },
    { name: 'Crimson Red', hex: '#DC143C' },
    { name: 'Baby Pink', hex: '#F4C2C2' },
    { name: 'Olive Green', hex: '#808000' },
    { name: 'Forest Green', hex: '#228B22' },
    { name: 'Mint Green', hex: '#98FF98' },
    { name: 'Beige', hex: '#F5F5DC' },
    { name: 'Mustard Yellow', hex: '#FFDB58' },
    { name: 'Lavender', hex: '#E6E6FA' },
    { name: 'Plum', hex: '#DDA0DD' },
    { name: 'Peach', hex: '#FFE5B4' },
];

export const COMMON_PANTS_COLORS = [
    { name: 'Black', hex: '#000000' },
    { name: 'Khaki', hex: '#C3B091' },
    { name: 'Denim Blue', hex: '#1E3A8A' },
    { name: 'Dark Grey', hex: '#A9A9A9' },
    { name: 'Light Grey', hex: '#D3D3D3' },
    { name: 'White', hex: '#FFFFFF' },
    { name: 'Brown', hex: '#A52A2A' },
    { name: 'Olive', hex: '#556B2F' },
    { name: 'Navy', hex: '#000080' },
    { name: 'Beige', hex: '#F5F5DC' },
    { name: 'Burgundy', hex: '#800020' },
    { name: 'Stone', hex: '#8B8C7A' },
    { name: 'Charcoal', hex: '#36454F' },
];

// Conceptually, this acts as our 'assets' folder for the landing page visuals
export const LANDING_PAGE_IMAGES = [
    'https://images.pexels.com/photos/15099685/pexels-photo-15099685.jpeg',
    'https://images.pexels.com/photos/29261349/pexels-photo-29261349.jpeg',
    'https://images.pexels.com/photos/29509894/pexels-photo-29509894.jpeg',
    'https://images.pexels.com/photos/29611425/pexels-photo-29611425.jpeg',
    'https://images.pexels.com/photos/29636303/pexels-photo-29636303.jpeg',
    'https://images.pexels.com/photos/2890747/pexels-photo-2890747.jpeg',
    'https://images.pexels.com/photos/15073750/pexels-photo-15073750.jpeg',
    'https://images.pexels.com/photos/18184057/pexels-photo-18184057.jpeg',
    'https://images.pexels.com/photos/13156810/pexels-photo-13156810.jpeg',
    'https://images.pexels.com/photos/15073762/pexels-photo-15073762.jpeg',
    'https://images.pexels.com/photos/5163938/pexels-photo-5163938.jpeg',
    'https://images.pexels.com/photos/14875566/pexels-photo-14875566.jpeg'
];