// FIX: Imported Modality to use the correct enum for responseModalities.
import { GoogleGenAI, Type, Modality } from "@google/genai";
import { OutfitColors, TurbanSuggestion } from "../types";

const API_KEY = process.env.API_KEY;
if (!API_KEY) {
    throw new Error("API_KEY environment variable not set");
}
const ai = new GoogleGenAI({ apiKey: API_KEY });

// FIX: Changed parameter type from File to Blob to resolve a type error when calling this function with a Blob created from a data URL.
const fileToGenerativePart = async (file: Blob) => {
    const base64EncodedDataPromise = new Promise<string>((resolve) => {
        const reader = new FileReader();
        reader.onloadend = () => resolve((reader.result as string).split(',')[1]);
        reader.readAsDataURL(file);
    });
    return {
        inlineData: { data: await base64EncodedDataPromise, mimeType: file.type },
    };
};

export const getColorsFromImage = async (file: File): Promise<OutfitColors> => {
    const imagePart = await fileToGenerativePart(file);
    
    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash',
        contents: [
            {
                parts: [
                    { text: "Analyze the clothing in this image. Identify the primary color of the shirt and the pants. Ignore any logos or graphics. Provide the result as a JSON object with keys 'shirtColor' and 'pantsColor', containing their hex color codes." },
                    imagePart
                ]
            }
        ],
        config: {
            responseMimeType: "application/json",
            responseSchema: {
                type: Type.OBJECT,
                properties: {
                    shirtColor: { type: Type.STRING },
                    pantsColor: { type: Type.STRING }
                },
                required: ["shirtColor", "pantsColor"]
            }
        }
    });

    const text = response.text.trim();
    return JSON.parse(text);
};


export const getTurbanSuggestions = async (colors: OutfitColors): Promise<TurbanSuggestion[]> => {
    const prompt = `
        Given a shirt color of ${colors.shirtColor} and pants color of ${colors.pantsColor}, suggest 5 matching turban colors based on color theory (complementary, analogous, triadic).
        For each suggestion, provide a brief, one-sentence reason for the match.
        Return the result as a JSON array of objects, where each object has 'colorName', 'hexCode', and 'reason' properties.
    `;

    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash',
        contents: prompt,
        config: {
            responseMimeType: "application/json",
            responseSchema: {
                type: Type.ARRAY,
                items: {
                    type: Type.OBJECT,
                    properties: {
                        colorName: { type: Type.STRING },
                        hexCode: { type: Type.STRING },
                        reason: { type: Type.STRING }
                    },
                    required: ["colorName", "hexCode", "reason"]
                }
            }
        }
    });

    const text = response.text.trim();
    return JSON.parse(text);
};

// FIX: Changed parameter type from File to Blob to resolve a type error when calling this function with a Blob created from a data URL.
export const recolorTurban = async (file: Blob, newColor: string, turbanStyle: string): Promise<string> => {
    const imagePart = await fileToGenerativePart(file);

    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
            parts: [
                imagePart,
                { text: `Using the provided image, change the color of the turban to ${newColor}. The turban should be in a ${turbanStyle} style. It is very important to not change the person's face, skin tone, background, or clothing. Keep the original style, shadows, and lighting of the turban perfectly intact, only altering its color and tying style.` }
            ]
        },
        config: {
            // FIX: Used Modality.IMAGE enum instead of a string for responseModalities, adhering to API guidelines.
            responseModalities: [Modality.IMAGE],
        }
    });
    
    const firstPart = response.candidates?.[0]?.content?.parts[0];
    if (firstPart && 'inlineData' in firstPart && firstPart.inlineData) {
        return firstPart.inlineData.data;
    }

    throw new Error("No image was generated by the API.");
};

export const generateSikhLook = async (colors: OutfitColors, turbanColor: string, turbanStyle: string): Promise<string> => {
    const backgrounds = [
        "against a clean, minimalist soft gray studio background",
        "in a serene park with blurred foliage in the background",
        "in a modern art gallery with abstract paintings on the wall",
        "in a cozy cafe with warm, soft lighting",
        "on a vibrant city street at dusk, with bokeh lights",
        "against a textured concrete wall for an urban feel",
        "in a bright, airy loft with large windows",
        "in front of a bookshelf in a quiet library",
    ];
    const randomBackground = backgrounds[Math.floor(Math.random() * backgrounds.length)];

    const prompt = `
        Generate an aesthetic, modern, full-body portrait of a young Sikh man.
        He is wearing a plain, solid-colored t-shirt with the hex color ${colors.shirtColor}, and plain, solid-colored pants with the hex color ${colors.pantsColor}.
        His turban is a neat, stylish ${turbanStyle} turban with the hex color ${turbanColor}.
        The setting is ${randomBackground}.
        The overall vibe should be elegant, modern, and visually pleasing. The man should have a gentle, confident expression. High-quality, photorealistic style.
    `;

    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
            parts: [
                { text: prompt }
            ]
        },
        config: {
            responseModalities: [Modality.IMAGE],
        }
    });

    const firstPart = response.candidates?.[0]?.content?.parts[0];
    if (firstPart && 'inlineData' in firstPart && firstPart.inlineData) {
        return firstPart.inlineData.data;
    }

    throw new Error("No image was generated by the API.");
};
